/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SyaratRouteImport } from './routes/syarat'
import { Route as SingleOriginRouteImport } from './routes/single-origin'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as KomunitasRouteImport } from './routes/komunitas'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as KebijakanPrivasiRouteImport } from './routes/kebijakan-privasi'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BlendRouteImport } from './routes/blend'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SingleOriginSlugRouteImport } from './routes/single-origin.$slug'
import { Route as ProdukSlugRouteImport } from './routes/produk.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedAkunRouteImport } from './routes/_authenticated/akun'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedPesananSuksesOrderNumberRouteImport } from './routes/_authenticated/pesanan-sukses.$orderNumber'
import { Route as AuthenticatedAkunWishlistRouteImport } from './routes/_authenticated/akun.wishlist'
import { Route as AuthenticatedAkunReviewRouteImport } from './routes/_authenticated/akun.review'
import { Route as AuthenticatedAkunProfilRouteImport } from './routes/_authenticated/akun.profil'
import { Route as AuthenticatedAkunNotifikasiRouteImport } from './routes/_authenticated/akun.notifikasi'
import { Route as AuthenticatedAkunAlamatRouteImport } from './routes/_authenticated/akun.alamat'
import { Route as AuthenticatedAdminVoucherRouteImport } from './routes/_authenticated/admin/voucher'
import { Route as AuthenticatedAdminUlasanRouteImport } from './routes/_authenticated/admin/ulasan'
import { Route as AuthenticatedAdminPengaturanRouteImport } from './routes/_authenticated/admin/pengaturan'
import { Route as AuthenticatedAdminPembayaranRouteImport } from './routes/_authenticated/admin/pembayaran'
import { Route as AuthenticatedAdminPelangganRouteImport } from './routes/_authenticated/admin/pelanggan'
import { Route as AuthenticatedAdminOriginsRouteImport } from './routes/_authenticated/admin/origins'
import { Route as AuthenticatedAdminKategoriRouteImport } from './routes/_authenticated/admin/kategori'
import { Route as AuthenticatedAkunPesananIndexRouteImport } from './routes/_authenticated/akun.pesanan.index'
import { Route as AuthenticatedAdminProdukIndexRouteImport } from './routes/_authenticated/admin/produk.index'
import { Route as AuthenticatedAdminPesananIndexRouteImport } from './routes/_authenticated/admin/pesanan.index'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated/admin/blog.index'
import { Route as AuthenticatedAdminProdukBaruRouteImport } from './routes/_authenticated/admin/produk.baru'
import { Route as AuthenticatedAdminProdukIdRouteImport } from './routes/_authenticated/admin/produk.$id'
import { Route as AuthenticatedAdminPesananOrderNumberRouteImport } from './routes/_authenticated/admin/pesanan.$orderNumber'
import { Route as AuthenticatedAdminBlogBaruRouteImport } from './routes/_authenticated/admin/blog.baru'
import { Route as AuthenticatedAdminBlogIdRouteImport } from './routes/_authenticated/admin/blog.$id'
import { Route as AuthenticatedAkunPesananOrderNumberIndexRouteImport } from './routes/_authenticated/akun.pesanan.$orderNumber.index'
import { Route as AuthenticatedAkunPesananOrderNumberBayarRouteImport } from './routes/_authenticated/akun.pesanan.$orderNumber.bayar'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SyaratRoute = SyaratRouteImport.update({
  id: '/syarat',
  path: '/syarat',
  getParentRoute: () => rootRouteImport,
} as any)
const SingleOriginRoute = SingleOriginRouteImport.update({
  id: '/single-origin',
  path: '/single-origin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const KomunitasRoute = KomunitasRouteImport.update({
  id: '/komunitas',
  path: '/komunitas',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const KebijakanPrivasiRoute = KebijakanPrivasiRouteImport.update({
  id: '/kebijakan-privasi',
  path: '/kebijakan-privasi',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlendRoute = BlendRouteImport.update({
  id: '/blend',
  path: '/blend',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SingleOriginSlugRoute = SingleOriginSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SingleOriginRoute,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAkunRoute = AuthenticatedAkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedPesananSuksesOrderNumberRoute =
  AuthenticatedPesananSuksesOrderNumberRouteImport.update({
    id: '/pesanan-sukses/$orderNumber',
    path: '/pesanan-sukses/$orderNumber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAkunWishlistRoute =
  AuthenticatedAkunWishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => AuthenticatedAkunRoute,
  } as any)
const AuthenticatedAkunReviewRoute = AuthenticatedAkunReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedAkunRoute,
} as any)
const AuthenticatedAkunProfilRoute = AuthenticatedAkunProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedAkunRoute,
} as any)
const AuthenticatedAkunNotifikasiRoute =
  AuthenticatedAkunNotifikasiRouteImport.update({
    id: '/notifikasi',
    path: '/notifikasi',
    getParentRoute: () => AuthenticatedAkunRoute,
  } as any)
const AuthenticatedAkunAlamatRoute = AuthenticatedAkunAlamatRouteImport.update({
  id: '/alamat',
  path: '/alamat',
  getParentRoute: () => AuthenticatedAkunRoute,
} as any)
const AuthenticatedAdminVoucherRoute =
  AuthenticatedAdminVoucherRouteImport.update({
    id: '/voucher',
    path: '/voucher',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUlasanRoute =
  AuthenticatedAdminUlasanRouteImport.update({
    id: '/ulasan',
    path: '/ulasan',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPengaturanRoute =
  AuthenticatedAdminPengaturanRouteImport.update({
    id: '/pengaturan',
    path: '/pengaturan',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPembayaranRoute =
  AuthenticatedAdminPembayaranRouteImport.update({
    id: '/pembayaran',
    path: '/pembayaran',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPelangganRoute =
  AuthenticatedAdminPelangganRouteImport.update({
    id: '/pelanggan',
    path: '/pelanggan',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOriginsRoute =
  AuthenticatedAdminOriginsRouteImport.update({
    id: '/origins',
    path: '/origins',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKategoriRoute =
  AuthenticatedAdminKategoriRouteImport.update({
    id: '/kategori',
    path: '/kategori',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAkunPesananIndexRoute =
  AuthenticatedAkunPesananIndexRouteImport.update({
    id: '/pesanan/',
    path: '/pesanan/',
    getParentRoute: () => AuthenticatedAkunRoute,
  } as any)
const AuthenticatedAdminProdukIndexRoute =
  AuthenticatedAdminProdukIndexRouteImport.update({
    id: '/produk/',
    path: '/produk/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPesananIndexRoute =
  AuthenticatedAdminPesananIndexRouteImport.update({
    id: '/pesanan/',
    path: '/pesanan/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProdukBaruRoute =
  AuthenticatedAdminProdukBaruRouteImport.update({
    id: '/produk/baru',
    path: '/produk/baru',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProdukIdRoute =
  AuthenticatedAdminProdukIdRouteImport.update({
    id: '/produk/$id',
    path: '/produk/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPesananOrderNumberRoute =
  AuthenticatedAdminPesananOrderNumberRouteImport.update({
    id: '/pesanan/$orderNumber',
    path: '/pesanan/$orderNumber',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBlogBaruRoute =
  AuthenticatedAdminBlogBaruRouteImport.update({
    id: '/blog/baru',
    path: '/blog/baru',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBlogIdRoute =
  AuthenticatedAdminBlogIdRouteImport.update({
    id: '/blog/$id',
    path: '/blog/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAkunPesananOrderNumberIndexRoute =
  AuthenticatedAkunPesananOrderNumberIndexRouteImport.update({
    id: '/pesanan/$orderNumber/',
    path: '/pesanan/$orderNumber/',
    getParentRoute: () => AuthenticatedAkunRoute,
  } as any)
const AuthenticatedAkunPesananOrderNumberBayarRoute =
  AuthenticatedAkunPesananOrderNumberBayarRouteImport.update({
    id: '/pesanan/$orderNumber/bayar',
    path: '/pesanan/$orderNumber/bayar',
    getParentRoute: () => AuthenticatedAkunRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/auth': typeof AuthRoute
  '/blend': typeof BlendRoute
  '/blog': typeof BlogRouteWithChildren
  '/custom': typeof CustomRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/keranjang': typeof KeranjangRoute
  '/komunitas': typeof KomunitasRoute
  '/kontak': typeof KontakRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/single-origin': typeof SingleOriginRouteWithChildren
  '/syarat': typeof SyaratRoute
  '/tentang': typeof TentangRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/akun': typeof AuthenticatedAkunRouteWithChildren
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/single-origin/$slug': typeof SingleOriginSlugRoute
  '/admin/kategori': typeof AuthenticatedAdminKategoriRoute
  '/admin/origins': typeof AuthenticatedAdminOriginsRoute
  '/admin/pelanggan': typeof AuthenticatedAdminPelangganRoute
  '/admin/pembayaran': typeof AuthenticatedAdminPembayaranRoute
  '/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/admin/ulasan': typeof AuthenticatedAdminUlasanRoute
  '/admin/voucher': typeof AuthenticatedAdminVoucherRoute
  '/akun/alamat': typeof AuthenticatedAkunAlamatRoute
  '/akun/notifikasi': typeof AuthenticatedAkunNotifikasiRoute
  '/akun/profil': typeof AuthenticatedAkunProfilRoute
  '/akun/review': typeof AuthenticatedAkunReviewRoute
  '/akun/wishlist': typeof AuthenticatedAkunWishlistRoute
  '/pesanan-sukses/$orderNumber': typeof AuthenticatedPesananSuksesOrderNumberRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/blog/baru': typeof AuthenticatedAdminBlogBaruRoute
  '/admin/pesanan/$orderNumber': typeof AuthenticatedAdminPesananOrderNumberRoute
  '/admin/produk/$id': typeof AuthenticatedAdminProdukIdRoute
  '/admin/produk/baru': typeof AuthenticatedAdminProdukBaruRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/pesanan/': typeof AuthenticatedAdminPesananIndexRoute
  '/admin/produk/': typeof AuthenticatedAdminProdukIndexRoute
  '/akun/pesanan/': typeof AuthenticatedAkunPesananIndexRoute
  '/akun/pesanan/$orderNumber/bayar': typeof AuthenticatedAkunPesananOrderNumberBayarRoute
  '/akun/pesanan/$orderNumber/': typeof AuthenticatedAkunPesananOrderNumberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/auth': typeof AuthRoute
  '/blend': typeof BlendRoute
  '/blog': typeof BlogRouteWithChildren
  '/custom': typeof CustomRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/keranjang': typeof KeranjangRoute
  '/komunitas': typeof KomunitasRoute
  '/kontak': typeof KontakRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/single-origin': typeof SingleOriginRouteWithChildren
  '/syarat': typeof SyaratRoute
  '/tentang': typeof TentangRoute
  '/akun': typeof AuthenticatedAkunRouteWithChildren
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/single-origin/$slug': typeof SingleOriginSlugRoute
  '/admin/kategori': typeof AuthenticatedAdminKategoriRoute
  '/admin/origins': typeof AuthenticatedAdminOriginsRoute
  '/admin/pelanggan': typeof AuthenticatedAdminPelangganRoute
  '/admin/pembayaran': typeof AuthenticatedAdminPembayaranRoute
  '/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/admin/ulasan': typeof AuthenticatedAdminUlasanRoute
  '/admin/voucher': typeof AuthenticatedAdminVoucherRoute
  '/akun/alamat': typeof AuthenticatedAkunAlamatRoute
  '/akun/notifikasi': typeof AuthenticatedAkunNotifikasiRoute
  '/akun/profil': typeof AuthenticatedAkunProfilRoute
  '/akun/review': typeof AuthenticatedAkunReviewRoute
  '/akun/wishlist': typeof AuthenticatedAkunWishlistRoute
  '/pesanan-sukses/$orderNumber': typeof AuthenticatedPesananSuksesOrderNumberRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/blog/baru': typeof AuthenticatedAdminBlogBaruRoute
  '/admin/pesanan/$orderNumber': typeof AuthenticatedAdminPesananOrderNumberRoute
  '/admin/produk/$id': typeof AuthenticatedAdminProdukIdRoute
  '/admin/produk/baru': typeof AuthenticatedAdminProdukBaruRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/pesanan': typeof AuthenticatedAdminPesananIndexRoute
  '/admin/produk': typeof AuthenticatedAdminProdukIndexRoute
  '/akun/pesanan': typeof AuthenticatedAkunPesananIndexRoute
  '/akun/pesanan/$orderNumber/bayar': typeof AuthenticatedAkunPesananOrderNumberBayarRoute
  '/akun/pesanan/$orderNumber': typeof AuthenticatedAkunPesananOrderNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accessories': typeof AccessoriesRoute
  '/auth': typeof AuthRoute
  '/blend': typeof BlendRoute
  '/blog': typeof BlogRouteWithChildren
  '/custom': typeof CustomRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/keranjang': typeof KeranjangRoute
  '/komunitas': typeof KomunitasRoute
  '/kontak': typeof KontakRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/single-origin': typeof SingleOriginRouteWithChildren
  '/syarat': typeof SyaratRoute
  '/tentang': typeof TentangRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/akun': typeof AuthenticatedAkunRouteWithChildren
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/single-origin/$slug': typeof SingleOriginSlugRoute
  '/_authenticated/admin/kategori': typeof AuthenticatedAdminKategoriRoute
  '/_authenticated/admin/origins': typeof AuthenticatedAdminOriginsRoute
  '/_authenticated/admin/pelanggan': typeof AuthenticatedAdminPelangganRoute
  '/_authenticated/admin/pembayaran': typeof AuthenticatedAdminPembayaranRoute
  '/_authenticated/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/_authenticated/admin/ulasan': typeof AuthenticatedAdminUlasanRoute
  '/_authenticated/admin/voucher': typeof AuthenticatedAdminVoucherRoute
  '/_authenticated/akun/alamat': typeof AuthenticatedAkunAlamatRoute
  '/_authenticated/akun/notifikasi': typeof AuthenticatedAkunNotifikasiRoute
  '/_authenticated/akun/profil': typeof AuthenticatedAkunProfilRoute
  '/_authenticated/akun/review': typeof AuthenticatedAkunReviewRoute
  '/_authenticated/akun/wishlist': typeof AuthenticatedAkunWishlistRoute
  '/_authenticated/pesanan-sukses/$orderNumber': typeof AuthenticatedPesananSuksesOrderNumberRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/_authenticated/admin/blog/baru': typeof AuthenticatedAdminBlogBaruRoute
  '/_authenticated/admin/pesanan/$orderNumber': typeof AuthenticatedAdminPesananOrderNumberRoute
  '/_authenticated/admin/produk/$id': typeof AuthenticatedAdminProdukIdRoute
  '/_authenticated/admin/produk/baru': typeof AuthenticatedAdminProdukBaruRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/_authenticated/admin/pesanan/': typeof AuthenticatedAdminPesananIndexRoute
  '/_authenticated/admin/produk/': typeof AuthenticatedAdminProdukIndexRoute
  '/_authenticated/akun/pesanan/': typeof AuthenticatedAkunPesananIndexRoute
  '/_authenticated/akun/pesanan/$orderNumber/bayar': typeof AuthenticatedAkunPesananOrderNumberBayarRoute
  '/_authenticated/akun/pesanan/$orderNumber/': typeof AuthenticatedAkunPesananOrderNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessories'
    | '/auth'
    | '/blend'
    | '/blog'
    | '/custom'
    | '/kebijakan-privasi'
    | '/keranjang'
    | '/komunitas'
    | '/kontak'
    | '/reset-password'
    | '/shop'
    | '/single-origin'
    | '/syarat'
    | '/tentang'
    | '/admin'
    | '/akun'
    | '/checkout'
    | '/blog/$slug'
    | '/produk/$slug'
    | '/single-origin/$slug'
    | '/admin/kategori'
    | '/admin/origins'
    | '/admin/pelanggan'
    | '/admin/pembayaran'
    | '/admin/pengaturan'
    | '/admin/ulasan'
    | '/admin/voucher'
    | '/akun/alamat'
    | '/akun/notifikasi'
    | '/akun/profil'
    | '/akun/review'
    | '/akun/wishlist'
    | '/pesanan-sukses/$orderNumber'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/blog/baru'
    | '/admin/pesanan/$orderNumber'
    | '/admin/produk/$id'
    | '/admin/produk/baru'
    | '/admin/blog/'
    | '/admin/pesanan/'
    | '/admin/produk/'
    | '/akun/pesanan/'
    | '/akun/pesanan/$orderNumber/bayar'
    | '/akun/pesanan/$orderNumber/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessories'
    | '/auth'
    | '/blend'
    | '/blog'
    | '/custom'
    | '/kebijakan-privasi'
    | '/keranjang'
    | '/komunitas'
    | '/kontak'
    | '/reset-password'
    | '/shop'
    | '/single-origin'
    | '/syarat'
    | '/tentang'
    | '/akun'
    | '/checkout'
    | '/blog/$slug'
    | '/produk/$slug'
    | '/single-origin/$slug'
    | '/admin/kategori'
    | '/admin/origins'
    | '/admin/pelanggan'
    | '/admin/pembayaran'
    | '/admin/pengaturan'
    | '/admin/ulasan'
    | '/admin/voucher'
    | '/akun/alamat'
    | '/akun/notifikasi'
    | '/akun/profil'
    | '/akun/review'
    | '/akun/wishlist'
    | '/pesanan-sukses/$orderNumber'
    | '/admin'
    | '/admin/blog/$id'
    | '/admin/blog/baru'
    | '/admin/pesanan/$orderNumber'
    | '/admin/produk/$id'
    | '/admin/produk/baru'
    | '/admin/blog'
    | '/admin/pesanan'
    | '/admin/produk'
    | '/akun/pesanan'
    | '/akun/pesanan/$orderNumber/bayar'
    | '/akun/pesanan/$orderNumber'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accessories'
    | '/auth'
    | '/blend'
    | '/blog'
    | '/custom'
    | '/kebijakan-privasi'
    | '/keranjang'
    | '/komunitas'
    | '/kontak'
    | '/reset-password'
    | '/shop'
    | '/single-origin'
    | '/syarat'
    | '/tentang'
    | '/_authenticated/admin'
    | '/_authenticated/akun'
    | '/_authenticated/checkout'
    | '/blog/$slug'
    | '/produk/$slug'
    | '/single-origin/$slug'
    | '/_authenticated/admin/kategori'
    | '/_authenticated/admin/origins'
    | '/_authenticated/admin/pelanggan'
    | '/_authenticated/admin/pembayaran'
    | '/_authenticated/admin/pengaturan'
    | '/_authenticated/admin/ulasan'
    | '/_authenticated/admin/voucher'
    | '/_authenticated/akun/alamat'
    | '/_authenticated/akun/notifikasi'
    | '/_authenticated/akun/profil'
    | '/_authenticated/akun/review'
    | '/_authenticated/akun/wishlist'
    | '/_authenticated/pesanan-sukses/$orderNumber'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/blog/$id'
    | '/_authenticated/admin/blog/baru'
    | '/_authenticated/admin/pesanan/$orderNumber'
    | '/_authenticated/admin/produk/$id'
    | '/_authenticated/admin/produk/baru'
    | '/_authenticated/admin/blog/'
    | '/_authenticated/admin/pesanan/'
    | '/_authenticated/admin/produk/'
    | '/_authenticated/akun/pesanan/'
    | '/_authenticated/akun/pesanan/$orderNumber/bayar'
    | '/_authenticated/akun/pesanan/$orderNumber/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessoriesRoute: typeof AccessoriesRoute
  AuthRoute: typeof AuthRoute
  BlendRoute: typeof BlendRoute
  BlogRoute: typeof BlogRouteWithChildren
  CustomRoute: typeof CustomRoute
  KebijakanPrivasiRoute: typeof KebijakanPrivasiRoute
  KeranjangRoute: typeof KeranjangRoute
  KomunitasRoute: typeof KomunitasRoute
  KontakRoute: typeof KontakRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  SingleOriginRoute: typeof SingleOriginRouteWithChildren
  SyaratRoute: typeof SyaratRoute
  TentangRoute: typeof TentangRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syarat': {
      id: '/syarat'
      path: '/syarat'
      fullPath: '/syarat'
      preLoaderRoute: typeof SyaratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single-origin': {
      id: '/single-origin'
      path: '/single-origin'
      fullPath: '/single-origin'
      preLoaderRoute: typeof SingleOriginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komunitas': {
      id: '/komunitas'
      path: '/komunitas'
      fullPath: '/komunitas'
      preLoaderRoute: typeof KomunitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kebijakan-privasi': {
      id: '/kebijakan-privasi'
      path: '/kebijakan-privasi'
      fullPath: '/kebijakan-privasi'
      preLoaderRoute: typeof KebijakanPrivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blend': {
      id: '/blend'
      path: '/blend'
      fullPath: '/blend'
      preLoaderRoute: typeof BlendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single-origin/$slug': {
      id: '/single-origin/$slug'
      path: '/$slug'
      fullPath: '/single-origin/$slug'
      preLoaderRoute: typeof SingleOriginSlugRouteImport
      parentRoute: typeof SingleOriginRoute
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akun': {
      id: '/_authenticated/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AuthenticatedAkunRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/pesanan-sukses/$orderNumber': {
      id: '/_authenticated/pesanan-sukses/$orderNumber'
      path: '/pesanan-sukses/$orderNumber'
      fullPath: '/pesanan-sukses/$orderNumber'
      preLoaderRoute: typeof AuthenticatedPesananSuksesOrderNumberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akun/wishlist': {
      id: '/_authenticated/akun/wishlist'
      path: '/wishlist'
      fullPath: '/akun/wishlist'
      preLoaderRoute: typeof AuthenticatedAkunWishlistRouteImport
      parentRoute: typeof AuthenticatedAkunRoute
    }
    '/_authenticated/akun/review': {
      id: '/_authenticated/akun/review'
      path: '/review'
      fullPath: '/akun/review'
      preLoaderRoute: typeof AuthenticatedAkunReviewRouteImport
      parentRoute: typeof AuthenticatedAkunRoute
    }
    '/_authenticated/akun/profil': {
      id: '/_authenticated/akun/profil'
      path: '/profil'
      fullPath: '/akun/profil'
      preLoaderRoute: typeof AuthenticatedAkunProfilRouteImport
      parentRoute: typeof AuthenticatedAkunRoute
    }
    '/_authenticated/akun/notifikasi': {
      id: '/_authenticated/akun/notifikasi'
      path: '/notifikasi'
      fullPath: '/akun/notifikasi'
      preLoaderRoute: typeof AuthenticatedAkunNotifikasiRouteImport
      parentRoute: typeof AuthenticatedAkunRoute
    }
    '/_authenticated/akun/alamat': {
      id: '/_authenticated/akun/alamat'
      path: '/alamat'
      fullPath: '/akun/alamat'
      preLoaderRoute: typeof AuthenticatedAkunAlamatRouteImport
      parentRoute: typeof AuthenticatedAkunRoute
    }
    '/_authenticated/admin/voucher': {
      id: '/_authenticated/admin/voucher'
      path: '/voucher'
      fullPath: '/admin/voucher'
      preLoaderRoute: typeof AuthenticatedAdminVoucherRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ulasan': {
      id: '/_authenticated/admin/ulasan'
      path: '/ulasan'
      fullPath: '/admin/ulasan'
      preLoaderRoute: typeof AuthenticatedAdminUlasanRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pengaturan': {
      id: '/_authenticated/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AuthenticatedAdminPengaturanRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pembayaran': {
      id: '/_authenticated/admin/pembayaran'
      path: '/pembayaran'
      fullPath: '/admin/pembayaran'
      preLoaderRoute: typeof AuthenticatedAdminPembayaranRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pelanggan': {
      id: '/_authenticated/admin/pelanggan'
      path: '/pelanggan'
      fullPath: '/admin/pelanggan'
      preLoaderRoute: typeof AuthenticatedAdminPelangganRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/origins': {
      id: '/_authenticated/admin/origins'
      path: '/origins'
      fullPath: '/admin/origins'
      preLoaderRoute: typeof AuthenticatedAdminOriginsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kategori': {
      id: '/_authenticated/admin/kategori'
      path: '/kategori'
      fullPath: '/admin/kategori'
      preLoaderRoute: typeof AuthenticatedAdminKategoriRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/akun/pesanan/': {
      id: '/_authenticated/akun/pesanan/'
      path: '/pesanan'
      fullPath: '/akun/pesanan/'
      preLoaderRoute: typeof AuthenticatedAkunPesananIndexRouteImport
      parentRoute: typeof AuthenticatedAkunRoute
    }
    '/_authenticated/admin/produk/': {
      id: '/_authenticated/admin/produk/'
      path: '/produk'
      fullPath: '/admin/produk/'
      preLoaderRoute: typeof AuthenticatedAdminProdukIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pesanan/': {
      id: '/_authenticated/admin/pesanan/'
      path: '/pesanan'
      fullPath: '/admin/pesanan/'
      preLoaderRoute: typeof AuthenticatedAdminPesananIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/produk/baru': {
      id: '/_authenticated/admin/produk/baru'
      path: '/produk/baru'
      fullPath: '/admin/produk/baru'
      preLoaderRoute: typeof AuthenticatedAdminProdukBaruRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/produk/$id': {
      id: '/_authenticated/admin/produk/$id'
      path: '/produk/$id'
      fullPath: '/admin/produk/$id'
      preLoaderRoute: typeof AuthenticatedAdminProdukIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pesanan/$orderNumber': {
      id: '/_authenticated/admin/pesanan/$orderNumber'
      path: '/pesanan/$orderNumber'
      fullPath: '/admin/pesanan/$orderNumber'
      preLoaderRoute: typeof AuthenticatedAdminPesananOrderNumberRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/blog/baru': {
      id: '/_authenticated/admin/blog/baru'
      path: '/blog/baru'
      fullPath: '/admin/blog/baru'
      preLoaderRoute: typeof AuthenticatedAdminBlogBaruRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/blog/$id': {
      id: '/_authenticated/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/akun/pesanan/$orderNumber/': {
      id: '/_authenticated/akun/pesanan/$orderNumber/'
      path: '/pesanan/$orderNumber'
      fullPath: '/akun/pesanan/$orderNumber/'
      preLoaderRoute: typeof AuthenticatedAkunPesananOrderNumberIndexRouteImport
      parentRoute: typeof AuthenticatedAkunRoute
    }
    '/_authenticated/akun/pesanan/$orderNumber/bayar': {
      id: '/_authenticated/akun/pesanan/$orderNumber/bayar'
      path: '/pesanan/$orderNumber/bayar'
      fullPath: '/akun/pesanan/$orderNumber/bayar'
      preLoaderRoute: typeof AuthenticatedAkunPesananOrderNumberBayarRouteImport
      parentRoute: typeof AuthenticatedAkunRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminKategoriRoute: typeof AuthenticatedAdminKategoriRoute
  AuthenticatedAdminOriginsRoute: typeof AuthenticatedAdminOriginsRoute
  AuthenticatedAdminPelangganRoute: typeof AuthenticatedAdminPelangganRoute
  AuthenticatedAdminPembayaranRoute: typeof AuthenticatedAdminPembayaranRoute
  AuthenticatedAdminPengaturanRoute: typeof AuthenticatedAdminPengaturanRoute
  AuthenticatedAdminUlasanRoute: typeof AuthenticatedAdminUlasanRoute
  AuthenticatedAdminVoucherRoute: typeof AuthenticatedAdminVoucherRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBlogIdRoute: typeof AuthenticatedAdminBlogIdRoute
  AuthenticatedAdminBlogBaruRoute: typeof AuthenticatedAdminBlogBaruRoute
  AuthenticatedAdminPesananOrderNumberRoute: typeof AuthenticatedAdminPesananOrderNumberRoute
  AuthenticatedAdminProdukIdRoute: typeof AuthenticatedAdminProdukIdRoute
  AuthenticatedAdminProdukBaruRoute: typeof AuthenticatedAdminProdukBaruRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
  AuthenticatedAdminPesananIndexRoute: typeof AuthenticatedAdminPesananIndexRoute
  AuthenticatedAdminProdukIndexRoute: typeof AuthenticatedAdminProdukIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminKategoriRoute: AuthenticatedAdminKategoriRoute,
    AuthenticatedAdminOriginsRoute: AuthenticatedAdminOriginsRoute,
    AuthenticatedAdminPelangganRoute: AuthenticatedAdminPelangganRoute,
    AuthenticatedAdminPembayaranRoute: AuthenticatedAdminPembayaranRoute,
    AuthenticatedAdminPengaturanRoute: AuthenticatedAdminPengaturanRoute,
    AuthenticatedAdminUlasanRoute: AuthenticatedAdminUlasanRoute,
    AuthenticatedAdminVoucherRoute: AuthenticatedAdminVoucherRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminBlogIdRoute: AuthenticatedAdminBlogIdRoute,
    AuthenticatedAdminBlogBaruRoute: AuthenticatedAdminBlogBaruRoute,
    AuthenticatedAdminPesananOrderNumberRoute:
      AuthenticatedAdminPesananOrderNumberRoute,
    AuthenticatedAdminProdukIdRoute: AuthenticatedAdminProdukIdRoute,
    AuthenticatedAdminProdukBaruRoute: AuthenticatedAdminProdukBaruRoute,
    AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
    AuthenticatedAdminPesananIndexRoute: AuthenticatedAdminPesananIndexRoute,
    AuthenticatedAdminProdukIndexRoute: AuthenticatedAdminProdukIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAkunRouteChildren {
  AuthenticatedAkunAlamatRoute: typeof AuthenticatedAkunAlamatRoute
  AuthenticatedAkunNotifikasiRoute: typeof AuthenticatedAkunNotifikasiRoute
  AuthenticatedAkunProfilRoute: typeof AuthenticatedAkunProfilRoute
  AuthenticatedAkunReviewRoute: typeof AuthenticatedAkunReviewRoute
  AuthenticatedAkunWishlistRoute: typeof AuthenticatedAkunWishlistRoute
  AuthenticatedAkunPesananIndexRoute: typeof AuthenticatedAkunPesananIndexRoute
  AuthenticatedAkunPesananOrderNumberBayarRoute: typeof AuthenticatedAkunPesananOrderNumberBayarRoute
  AuthenticatedAkunPesananOrderNumberIndexRoute: typeof AuthenticatedAkunPesananOrderNumberIndexRoute
}

const AuthenticatedAkunRouteChildren: AuthenticatedAkunRouteChildren = {
  AuthenticatedAkunAlamatRoute: AuthenticatedAkunAlamatRoute,
  AuthenticatedAkunNotifikasiRoute: AuthenticatedAkunNotifikasiRoute,
  AuthenticatedAkunProfilRoute: AuthenticatedAkunProfilRoute,
  AuthenticatedAkunReviewRoute: AuthenticatedAkunReviewRoute,
  AuthenticatedAkunWishlistRoute: AuthenticatedAkunWishlistRoute,
  AuthenticatedAkunPesananIndexRoute: AuthenticatedAkunPesananIndexRoute,
  AuthenticatedAkunPesananOrderNumberBayarRoute:
    AuthenticatedAkunPesananOrderNumberBayarRoute,
  AuthenticatedAkunPesananOrderNumberIndexRoute:
    AuthenticatedAkunPesananOrderNumberIndexRoute,
}

const AuthenticatedAkunRouteWithChildren =
  AuthenticatedAkunRoute._addFileChildren(AuthenticatedAkunRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAkunRoute: typeof AuthenticatedAkunRouteWithChildren
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedPesananSuksesOrderNumberRoute: typeof AuthenticatedPesananSuksesOrderNumberRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAkunRoute: AuthenticatedAkunRouteWithChildren,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedPesananSuksesOrderNumberRoute:
    AuthenticatedPesananSuksesOrderNumberRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface SingleOriginRouteChildren {
  SingleOriginSlugRoute: typeof SingleOriginSlugRoute
}

const SingleOriginRouteChildren: SingleOriginRouteChildren = {
  SingleOriginSlugRoute: SingleOriginSlugRoute,
}

const SingleOriginRouteWithChildren = SingleOriginRoute._addFileChildren(
  SingleOriginRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessoriesRoute: AccessoriesRoute,
  AuthRoute: AuthRoute,
  BlendRoute: BlendRoute,
  BlogRoute: BlogRouteWithChildren,
  CustomRoute: CustomRoute,
  KebijakanPrivasiRoute: KebijakanPrivasiRoute,
  KeranjangRoute: KeranjangRoute,
  KomunitasRoute: KomunitasRoute,
  KontakRoute: KontakRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  SingleOriginRoute: SingleOriginRouteWithChildren,
  SyaratRoute: SyaratRoute,
  TentangRoute: TentangRoute,
  ProdukSlugRoute: ProdukSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
